sudo: required
services:
  - docker

before_install:
  - docker build -t char0x00/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  # - docker run char0x00/multi-docker-test yarn test -- --coverage
  - docker run -e CI=true char0x00/multi-docker-test yarn test

after_success:
  # Build prod versions of all projects
  - docker build -t char0x00/multi-docker-client ./client
  - docker build -t char0x00/multi-docker-nginx ./nginx
  - docker build -t char0x00/multi-docker-server ./server
  - docker build -t char0x00/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push char0x00/multi-docker-client
  - docker push char0x00/multi-docker-nginx 
  - docker push char0x00/multi-docker-server
  - docker push char0x00/multi-docker-worker

# deploy to aws
# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: "ap-northeast-1"
#   app: "AWSEBDocker"
#   env: "Docker-env"
#   bucket_name: "S3 bucket name"
#   bucket_path: "AWSEBDocker"
#   on:
#     branch: master
#   # at travis setting
#   access_key_id: $AWS_ACCESS_KEY 
#   secret_access_key: $AWS_SECRET_KEY